#Default date format is "HH:mm:ss"
DateFormat: "HH:mm:ss"
UsePlaceholderAPI: true
MinPlayerMessage: "#000000For event %eventName% to start a minimum of %playerAmount% players must be online."

Tasks:
  0:
    #Event and Duration for placeholders
    #If you don't want to use, you can leave blank
    #Duration is second
    event: "Envoy"
    duration: 300
    time: "12:00:30"
    #You can type "Every" for everyday
    #MON, TUE, WED, THU, FRI, SAT, SUN
    day: "Every"
    #Play sound for every player
    sound: "BLOCK_BELL_USE"
    minPlayer: 0
    #Without "/"
    commands:
      - ""
      - ""
    webhooks:
      - webhook1
    subtasks:
      subtask-1:
        time: "12:00:20"
        commands:
          - "say 10 seconds left for Envoy!"
        webhooks:
          - webhook2
