#Default date format is "HH:mm:ss"
DateFormat: "HH:mm:ss"
UsePlaceholderAPI: true
MinPlayerMessage: "#000000For event %eventName% to start a minimum of %playerAmount% players must be online."

#Discord Webhook
#When event started
send-webhook: false
#Discord Server Settings -> Integrations -> Webhooks -> Select or create new webhook -> Copy webhook url -> Paste
webhook-url: ""
webhook-avatarURL: ""
webhook-content: "Test Content"
webhook-embeds:
  0:
    description: "Test Description"
    title: "Test Title"
    field:
      name: "TestName"
      value: "TestValue"
      inline: true
    #RGB color, use # first
    color: "#FFFFFF"

#Available placeholders
#%currentEvent%
#%nextEvent%
#%nextEventTime%
#%nextEventCountdown%

Tasks:
  0:
    #Event and Duration for placeholders
    #If you don't want to use, you can leave blank
    #Duration is second
    event: "Envoy"
    duration: 300
    time: "12:00:30"
    #You can type "Every" for everyday
    #MON, TUE, WED, THU, FRI, SAT, SUN
    day: "Every"
    #Play sound for every player
    sound: "BLOCK_BELL_USE"
    minPlayer: 0
    #Without "/"
    commands:
      - ""
      - ""


  1:
    remaining:
      active: true
      time: "12:00:00"
      commands:
        - "say 30 seconds before Envoy Event!"
    event: "Envoy"
    duration: 300
    time: "12:00:30"
    day: "TUE"
    sound: "BLOCK_BELL_USE"
    minPlayer: 15
    commands:
      - "say Hello players!"
