name: EventScheduler
version: '2.5.2-SNAPSHOT'
api-version: 1.16
main: com.notpatch.eventScheduler.EventScheduler
softdepend: [ PlaceholderAPI ]

commands:
  eventscheduler:
    permission: eventscheduler.admin
    description: Reload config.
  events: