name: EventScheduler
version: '2.5.1-SNAPSHOT'
api-version: 1.16
main: com.notpatch.eventScheduler.EventScheduler
softdepend: [PlaceholderAPI]

commands:
  eventscheduler:
    permission: eventscheduler.admin
    description: Reload config.