name: EventScheduler
version: '2.3-SNAPSHOT'
main: com.notpatch.eventScheduler.EventScheduler
softdepend: [PlaceholderAPI]

commands:
  eventscheduler:
    permission: eventscheduler.admin
    description: Reload config.