name: EventScheduler
version: '2.6.7'
api-version: 1.16
main: com.notpatch.eventScheduler.EventScheduler
softdepend: [ PlaceholderAPI ]

commands:
  eventscheduler:
    permission: eventscheduler.admin
    description: Reload config.
  events:
    description: List all events.